### ISSUE TITLE
BotInfo cog adds [p]info but Red already has that command.

### ISSUE THREAD

**Issue by The1stVoidRunner** [tekulvw/Squid-Plugins#18]
Like i said in the title the BotInfo cog adds a info command but Red already has one.

**Comment by gutigen** [comment]
Can confirm:

```
Copying botinfo...
[25/07/2016 20:33] ERROR owner load 73: Command info is already registered.
Traceback (most recent call last):
  File "/root/Red-DiscordBot/cogs/owner.py", line 64, in load
    self._load_cog(module)
  File "/root/Red-DiscordBot/cogs/owner.py", line 532, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "/usr/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 719, in load_extension
    lib.setup(self)
  File "/root/Red-DiscordBot/cogs/botinfo.py", line 173, in setup
    bot.add_cog(n)
  File "/usr/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 637, in add_cog
    self.add_command(member)
  File "/usr/lib/python3.5/site-packages/discord/ext/commands/core.py", line 463, in add_command
    raise discord.ClientException('Command {0.name} is already registered.'.format(command))
discord.errors.ClientException: Command info is already registered.
Traceback (most recent call last):
  File "/root/Red-DiscordBot/cogs/owner.py", line 64, in load
    self._load_cog(module)
  File "/root/Red-DiscordBot/cogs/owner.py", line 532, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "/usr/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 719, in load_extension
    lib.setup(self)
  File "/root/Red-DiscordBot/cogs/botinfo.py", line 173, in setup
    bot.add_cog(n)
  File "/usr/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 637, in add_cog
    self.add_command(member)
  File "/usr/lib/python3.5/site-packages/discord/ext/commands/core.py", line 463, in add_command
    raise discord.ClientException('Command {0.name} is already registered.'.format(command))
discord.errors.ClientException: Command info is already registered.
```

**Comment by tekulvw** [comment]
Yeah I'm aware. Using this on Squid I remove the info command from general. Not fixing.
