### ISSUE TITLE
permissions cog issue with cog update

### ISSUE THREAD

**Issue by Aioxas** [tekulvw/Squid-Plugins#21]
Posted below is the traceback that leads to this. As you can see, team is a command from irdumb's adventure cog. 

After setting pems for a command and uninstalling the cog that the command is contained in, then doing a cog update and saying yes to reload all. 

This is fixable by deleting the command from the perms.json or reinstalling the cog, telling the bot to remove any perms related to that command, and uninstalling it again. Another last resort is to do perms reset.

Also. This causes the cog to not be reloaded/loaded. So it has to be manually loaded.

[24/08/2016 22:08] ERROR red on_command_error 88: Exception in command 'cog update'
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Ram\cogs\permissions.py", line 141, in pred
    return func(*args, **kwargs)
  File "C:\Users\USER\Desktop\Ram\cogs\permissions.py", line 170, in _get_command
    ret = self.bot.commands[cmd.pop(0)]
KeyError: 'team'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\USER\Desktop\Ram\cogs\downloader.py", line 171, in update
    self.bot.unload_extension("cogs." + cog)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 732, in unload_extension
    self.remove_cog(cogname)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 703, in remove_cog
    unloader()
  File "C:\Users\USER\Desktop\Ram\cogs\permissions.py", line 112, in __unload
    cmd = self._get_command(cmd_dot)
  File "C:\Users\USER\Desktop\Ram\cogs\permissions.py", line 143, in pred
    raise exc from e
cogs.permissions.BadCommand
Ignoring exception in member_join
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\bot.py", line 247, in _run_extra
    yield from coro(*args, **kwargs)
  File "C:\Users\USER\Desktop\Ram\cogs\welcome.py", line 100, in member_join
    if self.speak_permissions(server):
  File "C:\Users\USER\Desktop\Ram\cogs\welcome.py", line 112, in speak_permissions
    return server.get_member(self.bot.user.id).permissions_in(channel).send_messages
  File "C:\Users\USER\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\user.py", line 119, in permissions_in
    return channel.permissions_for(self)
AttributeError: 'NoneType' object has no attribute 'permissions_for'

**Comment by tekulvw** [comment]
should be fixed with 68bc860
