### ISSUE TITLE
RSS cog returns invalid argument

### ISSUE THREAD

**Issue by pwnulatr** [tekulvw/Squid-Plugins#25]
Upon attempting to add a new RSS feed, the bot raises the following error: 
```
raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType
```
Here is the entire log of the error if it helps:

```
[01/09/2016 18:31] ERROR red on_command_error 88: Exception in command 'rss add'
Traceback (most recent call last):
  File "...rss.py", line 129, in _get_feed
    async with session.get(url) as r:
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\client.py", line 539, in __aenter__
    self._resp = yield from self._coro
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\client.py", line 187, in _request
    yield from resp.start(conn, read_until_eof)
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\client_reqrep.py", line 606, in start
    message = yield from httpstream.read()
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\streams.py", line 591, in read
    result = yield from super().read()
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\streams.py", line 446, in read
    yield from self._waiter
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\asyncio\futures.py", line 266, in result
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "...rss.py", line 158, in _rss_add
    await self.bot.say('Invalid or unavailable URL.')
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 288, in _augmented_msg
    msg = yield from coro
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 827, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "C:\Users\Pwnulatr\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 257, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType```

**Comment by tekulvw** [comment]
Fixed with 802dc13d
