### ISSUE TITLE
Events need to be comparable

### ISSUE THREAD

**Issue by tekulvw** [tekulvw/Squid-Plugins#5]
```
Task exception was never retrieved
future: <Task finished coro=<Scheduler.queue_manager() done, defined at C:\Users\Will\Desktop\Red-DiscordBot\cogs\scheduler.py:222> exception=TypeError('unorderable types: Event() < Event()',)>
Traceback (most recent call last):
  File "C:\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Will\Desktop\Red-DiscordBot\cogs\scheduler.py", line 226, in queue_manager
    next_tuple = await self.queue.get()
  File "C:\Python35\lib\asyncio\queues.py", line 176, in get
    return self.get_nowait()
  File "C:\Python35\lib\asyncio\queues.py", line 185, in get_nowait
    item = self._get()
  File "C:\Python35\lib\asyncio\queues.py", line 235, in _get
    return heappop(self._queue)
TypeError: unorderable types: Event() < Event()
```

**Comment by tekulvw** [comment]
fixed
