### ISSUE TITLE
Error in command 'rss add'

### ISSUE THREAD

**Issue by Alderander** [tekulvw/Squid-Plugins#63]
Hi,
when i write `!rss add news https://forum-en.guildwars2.com/forum/info/news.rss`
i have this error:
`Error in command 'rss add'. Check your console or logs for details.`
and traceback:

> 
> Exception in command 'rss add'
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/core.py", line 50, in wrapped
>     ret = yield from coro(*args, **kwargs)
>   File "/home/admin/web/mg/Red-DiscordBot/cogs/rss.py", line 155, in _rss_add
>     self.feeds.add_feed(ctx, name, url)
>   File "/home/admin/web/mg/Red-DiscordBot/cogs/rss.py", line 68, in add_feed
>     server = ctx.message.server.id
> AttributeError: 'NoneType' object has no attribute 'id'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "lib/discord/ext/commands/bot.py", line 846, in process_commands
>     yield from command.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 634, in invoke
>     yield from ctx.invoked_subcommand.invoke(ctx)
>   File "lib/discord/ext/commands/core.py", line 374, in invoke
>     yield from injected(*ctx.args, **ctx.kwargs)
>   File "lib/discord/ext/commands/core.py", line 54, in wrapped
>     raise CommandInvokeError(e) from e
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
> 

Why the command does not work? Everything else works without problems. Any solution for this cog?
Thanks

**Comment by Alderander** [comment]
resolved
