### ISSUE TITLE
Reactroles

### ISSUE THREAD

**Issue by VenomXIX** [tekulvw/Squid-Plugins#81]
Error Loading

Exception during loading of cog
Traceback (most recent call last):
  File "/home/red/.local/lib/python3.6/site-packages/redbot/core/core_commands.py", line 95, in _load
    await bot.load_extension(spec)
  File "/home/red/.local/lib/python3.6/site-packages/redbot/core/bot.py", line 220, in load_extension
    lib = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/red/.local/share/Red-DiscordBot/cogs/CogManager/cogs/reactrole/__init__.py", line 1, in <module>
    from .reactrole import ReactRole
  File "/home/red/.local/share/Red-DiscordBot/cogs/CogManager/cogs/reactrole/reactrole.py", line 44, in <module>
    class ReactRole:
  File "/home/red/.local/share/Red-DiscordBot/cogs/CogManager/cogs/reactrole/reactrole.py", line 286, in ReactRole
    async def on_raw_reaction_add(self, emoji: discord.PartialReactionEmoji,
AttributeError: module 'discord' has no attribute 'PartialReactionEmoji'

**Comment by w3bb** [comment]
Exact same issue.
